VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICollection"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit


'********************************************************************
'   Description:    Function to return all the items stored in this
'                   collection.
'********************************************************************
Public Function getItems() As Collection
End Function


'********************************************************************
'   Description:    Function to return the number of items stored in
'                   this collection.
'********************************************************************
Public Function count() As Long
End Function


'********************************************************************
'   Description:    Removes all the items from this collection.
'********************************************************************
Public Sub clear()
End Sub
