VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICollectionItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit



'********************************************************************
'   Function:       getProperty
'   Description:    Return the specified property of this item.
'********************************************************************
Public Function getProperty(propertyName As String) As Variant
End Function



'********************************************************************
'   Function:       setProperty
'   Description:    Updates the specified property of this item with
'                   the specified value.
'********************************************************************
Public Sub setProperty(propertyName As String, propertyValue As Variant)
End Sub
